import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learning Next.js with TypeScript",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">

               <body className={inter.className}>
               <div className="bg-yellow-300 p-5"><h1>This is the header</h1></div>

                {children}
                
                    <div className="bg-slate-600 p-5"><h1>This is the footer</h1></div>
                </body>
   
    </html>
  );
}
